### ISSUE TITLE
Is there anyway to output a color-image of differ instead of black-white?

### ISSUE THREAD

**Issue by YandexStudio** [nicolashahn/diffimg#1]
For example,
A<sub>1,1</sub> is (255,64,0)
B<sub>1,1</sub> is (80,160,0)
so output differ is
Out<sub>1,1</sub> (|255-80|,|64-160|,|0-0|)=(175,96,0)

**Comment by nicolashahn** [comment]
Hey YandexStudio, you should be getting color images by default. Have you tried on multiple sets of images? If so, can you send me a pair of that produces black and white output, where the original pictures are in color?

**Comment by YandexStudio** [comment]
Emmmm, one pair is my origin game screenshot and its lossy compressed one, another pair is pure color, both of them returns black-white result.

game-screenshot origin
<img src="https://res.cloudinary.com/yandex/image/upload/v1532490634/input_l6hzwa.png">

game-screenshot lossy compressed
<img src="https://res.cloudinary.com/yandex/image/upload/v1532490634/input01_iyniav.png">

game -screenshot diff result
<img src="https://res.cloudinary.com/yandex/image/upload/v1532490621/output_fq4h6l.png">

pure color input 01
<img src="https://res.cloudinary.com/yandex/image/upload/v1532490849/input03_fcdwjm.png">

pure color input 02
<img src="https://res.cloudinary.com/yandex/image/upload/v1532490849/input02_hspzpu.png">

pure color diff result
<img src="https://res.cloudinary.com/yandex/image/upload/v1532490849/output01_h1li1g.png">

Environment:
Ubuntu 18.04 under WSL, Winows 10 1803
I use the default command
`pip install diffimg`
`diffimg input.png input01.png output.png`

**Comment by nicolashahn** [comment]
Here are the results I get when diffing your images (the first two would not work until I removed the alpha channel from the first image - I need to add to the docs that images must be the same size and have the same channels):

![yandex_1_2_diff](https://user-images.githubusercontent.com/9121818/43180368-c1ffcb58-8fa5-11e8-9686-0bbd24ecf6bf.jpg)

![yandex_3_4_diff](https://user-images.githubusercontent.com/9121818/43180370-c6e84032-8fa5-11e8-87c5-f98fcb18f0e4.jpg)

I'm not sure why yours are different, or why PIL did not complain for you about the alpha channel difference in the first pair of pictures. I think this may have to do with using WSL. I'll try to test it on a similar environment as well.

**Comment by YandexStudio** [comment]
Could you please tell all the dependency of this tool?
I only installed `graphviz` ( in Ubuntu under WSL, I run `diffimg` and it said command not found, suggesting me install this, after install this, it can runs, but in CentOS, the system don't show any suggestions with "maybe missed package", just retruns "command not found" and I manually install this) 
I've tried on CentOS 7 and also returns black-white result.
Also, this time I removed alpha channel with
`convert input.png -alpha off input-no-alpha.png`
So I think this issue may not related with alpha channel, I think maybe I lose some dependence package, and maybe that cause this.

**Comment by nicolashahn** [comment]
My `diffimg` is not available as a standalone shell command, only through python. The way to run it is:

```
python -m diffimg <im1> <im2>
```
I believe you are using this `diffimg`: https://manpages.debian.org/jessie/graphviz/diffimg.1.en.html

The only dependency is the python library `pillow` which should be installed if you did `pip install diffimg`.

**Comment by nicolashahn** [comment]
@YandexStudio Did this solve your problem?

**Comment by YandexStudio** [comment]
Yes, it works now, correctly. But why if I don't specify a output file name，it then output a JPG？I think the differ shouldn't be compressed.

**Comment by nicolashahn** [comment]
@YandexStudio That's an excellent point. I've just pushed a version that allows you to save the diff image as a `.png` and preserve the alpha channel. I have not changed the default output name yet, but I think you're right that it should eventually be the default. On the next major version (0.2.0) I'll have it be `.png` by default, I think the 0.1.x versions should not change the defaults as to not break anything for current users.

For now, specify the `.png` extension manually and I think you should be able to achieve what you want.

Thanks for your suggestion though. Is there anything else about the module that isn't ideal for your workflow? If not, I'll close the issue.

**Comment by YandexStudio** [comment]
No, I think currently all my questions are solved. Thanks for your patience.
