### ISSUE TITLE
Difference ratio calculated incorrectly

### ISSUE THREAD

**Issue by baldurk** [nicolashahn/diffimg#2]
Hey! Thanks for this repo, it pointed me in the direction of PIL which I could use to solve a similar sort of problem :smile:.

One thing I noticed was that the difference was calculated based on a factor of 100 as the maximum difference:

https://github.com/nicolashahn/diffimg/blob/5a5293dd5fb8d17f32bb3167e48b8cfa5165966e/diffimg/__init__.py#L46-L51

But for normal RGB the values are in the range 0-255, so the difference could be up to 255. You can repro this with a script that generates black and white images and diffs them (which should print 1.0):

```
>>> import diffimg
>>> import PIL
>>> PIL.Image.new('RGB', (10,10), (0,0,0)).save('a.png')
>>> PIL.Image.new('RGB', (10,10), (255,255,255)).save('b.png')
>>> diffimg.diff('a.png', 'b.png')
2.55
```

**Comment by nicolashahn** [comment]
Ooof, that's a pretty bad oversight on my part. I'll fix this ASAP, thanks for bringing it to my attention.

**Comment by nicolashahn** [comment]
Version 0.2.0 has this change - let me know if you notice anything else.
