### ISSUE TITLE
difference image is not convenient for png

### ISSUE THREAD

**Issue by BenjaminHabert** [nicolashahn/diffimg#3]
I am using this tool to measure the difference between two png files. The alpha of each pixel of both images is 255. Consequently the diff image produced by `ImageChops.difference()` is completely transparent. This is not convenient to locate differences between the two images.

**Comment by nicolashahn** [comment]
You're right, and I actually have a different implementation that has a feature `ignorealpha` which will let you locate differences between opaque PNGs: https://github.com/nicolashahn/diffimg-go

I will add the same feature to the python (this) implementation as well when I get a chance.

**Comment by nicolashahn** [comment]
@BenjaminHabert I just pushed a new version (0.2.3) which adds the flag `--ignore-alpha`. Can you test and see if this gives you what you need?

**Comment by BenjaminHabert** [comment]
I just tested with the 0.2.3 version using the `ignore_alpha=True` argument of `diffimg.diff()`. I obtained the expected result.

Thank you for the quick update!
