### ISSUE TITLE
Different size not taken into account. Is it possible to scale one to the format or size of the other?

### ISSUE THREAD

**Issue by jheinitz** [nicolashahn/diffimg#4]
Hello,

I came accross your module and find it quite useful. For my usecase I would need a feature to compare even images with different sizes because I receive pictures from different sources showing the same scene. I would like to see these images to be considered "similar" (lower percentage or ratio). 

Would that be possible?

Kind regards

Jens

**Comment by nicolashahn** [comment]
For an immediate solution you could add a step before using diffimg that rescales one of the images to match the other (using PIL or Imagemagick for example), but I'll consider adding that to diffimg itself.

**Comment by nicolashahn** [comment]
0.3.0 now resizes the 2nd image to match the 1st before calculation. Hopefully this solves your problem!
